### ISSUE TITLE
请教大佬，字符显示为带框的X，应该如何设置？

### ISSUE THREAD

**Issue by tongnixcv** [lxgw/LxgwWenKai-Screen#10]
![Clip_20230308_150434](https://user-images.githubusercontent.com/44078465/223646086-a33b0fc2-5c17-4b8e-94c2-02b8b6853bf8.png)

如图所示，感谢回复！

**Comment by lxgw** [comment]
Firefox 的「无视其他字体」功能可能会把网页内的图标字体覆盖。

**Comment by tongnixcv** [comment]
> 

chrome 有什么好方法吗？主力浏览器是它

**Comment by lxgw** [comment]
> > 
> 
> chrome 有什么好方法吗？主力浏览器是它

如果您认为是字体存在问题，请更换其他字体。

**Comment by lxgw** [comment]
> > 
> 
> chrome 有什么好方法吗？主力浏览器是它

如果您认为是字体存在问题，请您选用其他字体。
