### ISSUE TITLE
字体宽度

### ISSUE THREAD

**Issue by m3lab-zzl** [lxgw/LxgwWenKai-Screen#4]
Screen版本的字体构造精美，但是宽度似乎不足。

宽度据说有所增加，但是在PC上的实际显示效果依然差强人意。

对比微软雅黑搭配Arial的渲染效果，由于字体偏细，浏览时较吃力。

![本字体](https://user-images.githubusercontent.com/102862066/182517706-95e83854-114e-4598-b943-bf0fdf77e6ab.png)

![微软雅黑](https://user-images.githubusercontent.com/102862066/182517722-afe38e08-ad5f-4ede-99c2-21f602fe5af8.png)

建议将字体宽度调整到与微软雅黑的一致。

**Comment by lxgw** [comment]
像 Klee 字体本就偏纤细，而且中宫偏小，这也就决定了不能像黑体那样很大限度地加粗，而且再加粗的话很多笔画较多的字会糊掉，还不如系统渲染加粗。

（曾经为解决这个问题，开启了 [霞鹜臻楷](https://github.com/lxgw/LxgwZhenKai) 项目对这款字体进行手工加粗调整，先从常用字开始尝试，目标是为了加粗完简体（繁体笔画普遍繁多，调整起来工作量更大），为了防止糊掉或粘连，一个字一个字调整，结果在字重的选择上还是保守，加粗幅度选得还是小了，直接机械加粗又怕糊掉。由于这个项目并未达到预期效果，个人觉得没必要在这种没有结果的事情上再浪费时间和精力，于是不再更新。）

所以，限于本人目前的空余时间及个人技术水平，恕无法满足您的需求，抱歉。

**Comment by m3lab-zzl** [comment]
辛苦了，那这个字体就暂时不用作浏览器的默认显示字体吧。

另外，差强人意表示勉强可以接受，我正是此意。
