### ISSUE TITLE
v1.235之后的版本字体在web竖向显示时高度塌陷

### ISSUE THREAD

**Issue by lyswhut** [lxgw/LxgwWenKai-Screen#5]
重现方式：

1. 从[release](https://github.com/lxgw/LxgwWenKai-Screen/releases/tag/v1.245)下载 v1.245的 `LXGWWenKaiScreen.ttf`文件
2. 在下载的字体目录下新建一个包含以下内容的`index.html`文件：
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Document</title>
  </head>
  <style>
    @font-face {
      font-family: 'LxgwWenKai-Screen';
      src: url('./LXGWWenKaiScreen.ttf');
    }

    h1 { font-size: 36px;  font-family: "LxgwWenKai-Screen"; }
    .vertical { writing-mode: vertical-rl; }

  </style>
  <body>
    <h1>测试字体</h1>
    <h1 class="vertical">测试字体</h1>
  </body>

</html>
```
3. 用浏览器打开这个文件即可看到效果：
![image](https://user-images.githubusercontent.com/20365169/201506366-17231eb7-af53-49bb-94e9-ee86abd144c8.png)

4. 将 `LXGWWenKaiScreen.ttf` 文件替换成 [v1.235](https://github.com/lxgw/LxgwWenKai-Screen/releases/tag/v1.235) 版本即可恢复正常：
![image](https://user-images.githubusercontent.com/20365169/201506430-3316bff0-f0ac-41ed-b8b5-84e30a623d64.png)

另外，刚试了下非屏幕阅读版的`LXGWWenKai-Regular.ttf`字体高度也是正常的

**Comment by lxgw** [comment]
下个版本修复。

另外，不建议使用该字体作竖向排版。

**Comment by lyswhut** [comment]
谢谢:)

> 另外，不建议使用该字体作竖向排版。

我也很少用竖向排版，只是在测试的时候发现有问题就顺便提了一下😄
