### ISSUE TITLE
关于等宽版本

### ISSUE THREAD

**Issue by airinghost** [lxgw/LxgwWenKai-Screen#7]
霞鹜大侠晚上好哇。请问霞鹜文楷屏幕阅读版后续有计划添加等宽版本吗？

**Comment by lxgw** [comment]
目前没有。这款字体主要是用在手机显示上，故只有非等宽。

**Comment by airinghost** [comment]
> 目前没有。这款字体主要是用在手机显示上，故只有非等宽。

嗷嗷，明白了
