### ISSUE TITLE
请问有 LxgwWenKai Lite 的屏幕版本吗？

### ISSUE THREAD

**Issue by tw93** [lxgw/LxgwWenKai-Screen#8]
你好，很感谢提供屏幕版本，我已经在我这边不少网页用上
不过，想请教一下，有 Lite 版本的吗？因为非Lite版本即使用WebFont其实也很大，不太适合网页了
此外，屏幕版本的粗体在字体大了时候显得有些过粗了，有办法变细一丢丢不
感谢！

**Comment by lxgw** [comment]
屏幕阅读版主要是为了用于手机，所以字库是相对全一点的，没有 Lite 版的计划。
