### ISSUE TITLE
v1.250似乎字重丢失

### ISSUE THREAD

**Issue by rLry** [lxgw/LxgwWenKai-Screen#9]
系统：windows11 22621.1105
起因是obsidian笔记内加粗部分全部消失，排除了笔记以及外观问题，发现Word 中常规和粗体没有区别。
因为我没有其他设备可供测试，想问一下这是否是bug或屏幕阅读版没有多字重了？谢谢。
![20230123_133942_WINWORD_src](https://user-images.githubusercontent.com/19667685/213973019-6a3e42d8-0e54-46c5-abbf-8b1a89698de1.png)

**Comment by lxgw** [comment]
因为加粗会更糊。

**Comment by rLry** [comment]
> 因为加粗会更糊。

好的，原来是取消字重了啊，那我找找前面的版本，谢谢

**Comment by lxgw** [comment]
看了一下，GB 版是可以加粗的。

稍后发布修复版本，请关注本项目的 Release 更新。

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwWenKai-Screen/releases/tag/v1.250.1

**Comment by ygxxii** [comment]
此问题在 MacOS 的 Obsidian 上貌似依然存在，GB 版 和 非GB版 在 Obsidian 上都无法显示加粗：

- MacOS 版本：13.1
- Obsidian 版本：v1.1.14
- 测试字体：
	- v1.250.2 GB：无法显示加粗
	- v1.250.2 非 GB：无法显示加粗
	- v1.250.1 GB：无法显示加粗
	- v1.250.1 非 GB：无法显示加粗

![image](https://user-images.githubusercontent.com/16456434/220571130-348a48fc-603f-4b54-93f7-6742ba70f657.png)

---

在 Obsidian 使用 Sarasa Gothic SC 作为对比：

![image](https://user-images.githubusercontent.com/16456434/220572441-347c9749-b9e1-48ea-aab3-957487cc77b2.png)


---

不过，在 MacOS 的 Word 上测试了一下，**是正常的**，能够显示加粗：

![image](https://user-images.githubusercontent.com/16456434/220571366-05f2f9bf-4992-4680-838d-4be400b6d86c.png)

**Comment by lxgw** [comment]
> 此问题在 MacOS 的 Obsidian 上貌似依然存在，GB 版 和 非GB版 在 Obsidian 上都无法显示加粗：
> 
> * MacOS 版本：13.1
> * Obsidian 版本：v1.1.14
> * 测试字体：
>   
>   * v1.250.2 GB：无法显示加粗
>   * v1.250.2 非 GB：无法显示加粗
>   * v1.250.1 GB：无法显示加粗
>   * v1.250.1 非 GB：无法显示加粗
> 
> ![image](https://user-images.githubusercontent.com/16456434/220571130-348a48fc-603f-4b54-93f7-6742ba70f657.png)
> 
> 在 Obsidian 使用 Sarasa Gothic SC 作为对比：
> 
> ![image](https://user-images.githubusercontent.com/16456434/220572441-347c9749-b9e1-48ea-aab3-957487cc77b2.png)
> 
> 不过，在 MacOS 的 Word 上测试了一下，**是正常的**，能够显示加粗：
> 
> ![image](https://user-images.githubusercontent.com/16456434/220571366-05f2f9bf-4992-4680-838d-4be400b6d86c.png)

实在抱歉，请您使用历史版本的该字体，或选用其他字体。
